# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 13:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('kodas', models.CharField(max_length=30, unique=True)),
                ('preke', models.CharField(max_length=100, unique=True, verbose_name='Prekė, paslauga, darbas')),
                ('islaidos', models.DecimalField(decimal_places=2, max_digits=9)),
                ('paslauga_darbas_preke', models.CharField(choices=[('paslauga', 'Paslauga'), ('darbas', 'Darbas'), ('preke', 'Prekė')], default='preke', max_length=8)),
                ('organizatorius', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name_plural': 'Planas',
                'ordering': ['kodas'],
                'verbose_name': 'Planas',
            },
            managers=[
                ('include_deleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Sf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf', models.CharField(max_length=50, unique=True, verbose_name='Sąskaitos faktūros Nr.')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Sąsk. faktūros suma')),
                ('data', models.DateField(verbose_name='Sąsk. faktūros data')),
                ('pavadinimas', models.CharField(max_length=255, verbose_name='Pirkimo objektas')),
            ],
            options={
                'verbose_name_plural': 'Sąskaitos faktūros',
                'verbose_name': 'Sąskaitos faktūros',
            },
        ),
        migrations.CreateModel(
            name='Sutartis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Sutarties data')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Planuojama Suma')),
                ('tiekejo_kodas', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Tiekėjo kodas')),
                ('tiekejas', models.CharField(max_length=100, verbose_name='Tiekėjas')),
                ('pastaba', models.CharField(blank=True, max_length=200, verbose_name='Pastaba')),
                ('zalias', models.BooleanField(default=False, verbose_name='Ar tai žalias pirkimas?')),
                ('kodas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vart.Planas', to_field='kodas', verbose_name='Kodas')),
            ],
            options={
                'verbose_name_plural': 'Sutartis',
                'verbose_name': 'Sutartis',
            },
        ),
        migrations.AddField(
            model_name='sf',
            name='sutartisid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vart.Sutartis'),
        ),
    ]
