# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodas', models.CharField(max_length=30)),
                ('preke', models.CharField(max_length=100)),
                ('islaidos', models.DecimalField(decimal_places=2, max_digits=9)),
                ('paslauga_darbas_preke', models.CharField(default='preke', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vartotojai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizatorius', models.CharField(max_length=50, unique=True)),
                ('pareigos', models.CharField(max_length=200)),
                ('adminas', models.BooleanField(default=False)),
                ('aktyvus', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='planas',
            name='organizatorius',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vart.Vartotojai', to_field='organizatorius'),
        ),
    ]
