# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planas',
            options={'verbose_name': 'Planas', 'verbose_name_plural': 'Planas'},
        ),
        migrations.AlterModelOptions(
            name='vartotojai',
            options={'verbose_name': 'Vartotojai', 'verbose_name_plural': 'Vartotojai'},
        ),
        migrations.AlterField(
            model_name='planas',
            name='paslauga_darbas_preke',
            field=models.CharField(choices=[('paslauga', 'Paslauga'), ('darbas', 'Darbas'), ('preke', 'Prekė')], default='preke', max_length=8),
        ),
    ]
