# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 05:25
from __future__ import unicode_literals

import braces.views._access
from django.db import migrations, models
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('vart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanasDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(braces.views._access.LoginRequiredMixin, django.views.generic.edit.DeleteView, models.Model),
        ),
        migrations.AlterField(
            model_name='sf',
            name='sf',
            field=models.CharField(max_length=50, verbose_name='Sąskaitos faktūros Nr.'),
        ),
    ]
