# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vart', '0003_auto_20160928_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planas',
            name='organizatorius',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
