# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vart', '0004_auto_20160928_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vartotojai',
        ),
        migrations.AlterModelOptions(
            name='planas',
            options={'ordering': ['kodas'], 'verbose_name': 'Planas', 'verbose_name_plural': 'Planas'},
        ),
        migrations.AlterField(
            model_name='planas',
            name='kodas',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
