# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 19:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vart', '0005_auto_20160930_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sutartis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Sutarties data')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Planuojama Suma')),
                ('tiekejo_kodas', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Tiekėjo kodas')),
                ('tiekejas', models.CharField(max_length=100, verbose_name='Tiekėjas')),
                ('pastaba', models.CharField(max_length=200, verbose_name='Pastaba')),
                ('zalias', models.BooleanField(default=False, verbose_name='Ar tai žalias pirkimas?')),
            ],
            options={
                'verbose_name': 'Sutartis',
            },
        ),
        migrations.AlterField(
            model_name='planas',
            name='preke',
            field=models.CharField(max_length=100, unique=True, verbose_name='Prekė, paslauga, darbas'),
        ),
        migrations.AddField(
            model_name='sutartis',
            name='kodas_sut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kodas_sut', to='vart.Planas', to_field='kodas', verbose_name='Kodas'),
        ),
        migrations.AddField(
            model_name='sutartis',
            name='preke_sut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preke_sut', to='vart.Planas', to_field='preke', verbose_name='Pavadinimas'),
        ),
    ]
