# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vart', '0006_auto_20161001_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sutartis',
            options={'verbose_name': 'Sutartis', 'verbose_name_plural': 'Sutartis'},
        ),
        migrations.RemoveField(
            model_name='sutartis',
            name='kodas_sut',
        ),
        migrations.RemoveField(
            model_name='sutartis',
            name='preke_sut',
        ),
        migrations.AddField(
            model_name='sutartis',
            name='kodas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vart.Planas', to_field='kodas', verbose_name='Kodas'),
        ),
    ]
