# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vart', '0010_auto_20161001_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='SF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf', models.CharField(max_length=50, unique=True, verbose_name='Sąskaitos faktūros Nr.')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Sąsk. faktūros suma')),
                ('data', models.DateField(verbose_name='Sąsk. faktūros data')),
                ('pavadinimas', models.CharField(max_length=255, verbose_name='Pirkimo objektas')),
            ],
        ),
        migrations.AlterField(
            model_name='sutartis',
            name='kodas',
            field=models.ForeignKey(default=111111, on_delete=django.db.models.deletion.CASCADE, to='vart.Planas', to_field='kodas', verbose_name='Kodas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sf',
            name='sutartisid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vart.Sutartis'),
        ),
    ]
